### PR TITLE
Be scraping update

### PR DESCRIPTION
**Pull request by Ethorf**
still trying to figure out how to get this function to return something! check out /utils/scrapingFunction.js

### CODE REVIEW

**Comment by surhud004** [comment]
This is an implementation of Puppeteer without promises and it returns data!
```
const puppeteer = require('puppeteer');

let _browser;
let _page;

puppeteer
  .launch()
  .then(browser => (_browser = browser))
  .then(browser => (_page = browser.newPage()))
  .then(page => page.goto('https://example.com'))
  .then(() => _page)
  .then(page => page.screenshot({ path: 'example.png' }))
  .then(() => _browser.close());
```

**Comment by Ethorf** [comment]
Hmm yeah that was the example I initially used to construct my scraper function, but that actually doesn't technically "return" data, it writes data to a new file (example.png), though I was considering that maybe being a workaround of some sort?

**Comment by surhud004** [comment]
Check this out - https://github.com/puppeteer/puppeteer/blob/main/examples/search.js

**Comment by Ethorf** [comment]
ah yeah that example is still console.logging the data not returning it, I have no problem getting the data to the console at all

**Comment by surhud004** [comment]
Don't worry @Ethorf @surhud004 to the rescue!! https://github.com/hatchways/team-watermelon/pull/27/commits/45c57d205ccfa8fa1df15f6bad71a741e039e181#diff-037473f3f56b1a01c1020e9f7f03f433

**Comment by Ethorf** [comment]
Okay so updated the scraping function, @surhud004 if you could try this one imported into your cron jobs scheduler when you can and we'll see if it's functional? Thank you!

**Review by surhud004 — APPROVED** [review]
It finally works lol

**Comment by Ethorf** [comment]
Okay so it should be updated and working now, @surhud004 confirm that it works in your cron jobs!

**Comment by surhud004** [comment]
> Okay so it should be updated and working now, @surhud004 confirm that it works in your cron jobs!

Checkout Slack!!

**Review by surhud004 — APPROVED** [review]
Works seamlessly... even for Amazon... we have a few images links in product schema hence returned undefined lol

**Pull request merged**
